<a href="https://colab.research.google.com/github/MichalBrodackiPJA/Eksploracja-i-Wizualizacja-Danych/blob/master/Mapreduce_Spark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!apt-get install openjdk-11-jdk-headless -qq > /dev/null

In [16]:
!wget -q https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz

In [17]:
!tar xf spark-3.5.0-bin-hadoop3.tgz

In [18]:
!pip install -q findspark
!pip install pyspark -q

In [23]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "./spark-3.5.0-bin-hadoop3"

In [24]:
import findspark

findspark.init()
findspark.find()

'./spark-3.5.0-bin-hadoop3'

In [25]:
from pyspark import SparkConf, SparkContext


conf = SparkConf().setMaster("local").setAppName("CustomerOrders")
sc=SparkContext(conf=conf)

In [26]:
def parse_line(line):
  ID, _, value = line.split(',')
  return ID, float(value)

lines = sc.textFile('customer-orders.csv')
pairs = lines.map(parse_line)
vals_per_item = pairs.reduceByKey(lambda x,y: x+y)
results = vals_per_item.collect()

for result in results:
  print(result)

('44', 4756.8899999999985)
('35', 5155.419999999999)
('2', 5994.59)
('47', 4316.299999999999)
('29', 5032.529999999999)
('91', 4642.259999999999)
('70', 5368.249999999999)
('85', 5503.43)
('53', 4945.299999999999)
('14', 4735.030000000001)
('51', 4975.22)
('42', 5696.840000000003)
('79', 3790.570000000001)
('50', 4517.27)
('20', 4836.859999999999)
('15', 5413.510000000001)
('5', 4561.069999999999)
('48', 4384.33)
('31', 4765.05)
('4', 4815.050000000002)
('36', 4278.049999999997)
('57', 4628.4)
('12', 4664.589999999998)
('22', 5019.449999999999)
('54', 6065.389999999999)
('0', 5524.949999999998)
('88', 4830.549999999999)
('86', 4908.81)
('13', 4367.62)
('40', 5186.429999999999)
('98', 4297.260000000001)
('55', 5298.090000000002)
('95', 4876.840000000002)
('61', 5497.479999999998)
('27', 4915.889999999999)
('78', 4524.509999999999)
('83', 4635.799999999997)
('6', 5397.879999999998)
('26', 5250.4)
('75', 4178.500000000001)
('25', 5057.610000000001)
('71', 5995.660000000003)
('39', 6193.109999999999)
('60', 5040.709999999999)
('97', 5977.189999999995)
('7', 4755.070000000001)
('21', 4707.41)
('69', 5123.010000000001)
('37', 4735.200000000002)
('1', 4958.600000000001)
('64', 5288.689999999996)
('82', 4812.489999999998)
('72', 5337.44)
('99', 4172.289999999998)
('34', 5330.8)
('73', 6206.199999999999)
('49', 4394.599999999999)
('8', 5517.240000000001)
('46', 5963.109999999999)
('23', 4042.6499999999987)
('19', 5059.4299999999985)
('65', 5140.3499999999985)
('80', 4727.860000000001)
('16', 4979.06)
('9', 5322.649999999999)
('18', 4921.27)
('59', 5642.89)
('74', 4647.129999999999)
('30', 4990.72)
('56', 4701.019999999999)
('90', 5290.409999999998)
('68', 6375.449999999997)
('11', 5152.290000000002)
('10', 4819.700000000001)
('41', 5637.62)
('58', 5437.7300000000005)
('87', 5206.4)
('17', 5032.679999999999)
('33', 5254.659999999998)
('62', 5253.3200000000015)
('92', 5379.280000000002)
('76', 4904.209999999999)
('66', 4681.919999999999)
('43', 5368.83)
('52', 5245.059999999999)
('77', 4327.729999999999)
('81', 5112.709999999999)
('84', 4652.939999999999)
('3', 4659.63)
('93', 5265.750000000001)
('89', 4851.479999999999)
('45', 3309.38)
('24', 5259.920000000003)
('96', 3924.230000000001)
('67', 4505.79)
('63', 5415.150000000001)
('94', 4475.569999999999)
('32', 5496.050000000004)
('38', 4898.460000000002)
('28', 5000.709999999998)

In [29]:
def get_value(line):
  return line[1]

lines = sc.textFile('customer-orders.csv')
pairs = lines.map(parse_line)
vals_per_item = pairs.reduceByKey(lambda x,y: x+y)
vals_per_item_sorted = vals_per_item.sortBy(get_value, ascending=True)
results = vals_per_item_sorted.collect()

for result in results:
  print(result)

('45', 3309.38)
('79', 3790.570000000001)
('96', 3924.230000000001)
('23', 4042.6499999999987)
('99', 4172.289999999998)
('75', 4178.500000000001)
('36', 4278.049999999997)
('98', 4297.260000000001)
('47', 4316.299999999999)
('77', 4327.729999999999)
('13', 4367.62)
('48', 4384.33)
('49', 4394.599999999999)
('94', 4475.569999999999)
('67', 4505.79)
('50', 4517.27)
('78', 4524.509999999999)
('5', 4561.069999999999)
('57', 4628.4)
('83', 4635.799999999997)
('91', 4642.259999999999)
('74', 4647.129999999999)
('84', 4652.939999999999)
('3', 4659.63)
('12', 4664.589999999998)
('66', 4681.919999999999)
('56', 4701.019999999999)
('21', 4707.41)
('80', 4727.860000000001)
('14', 4735.030000000001)
('37', 4735.200000000002)
('7', 4755.070000000001)
('44', 4756.8899999999985)
('31', 4765.05)
('82', 4812.489999999998)
('4', 4815.050000000002)
('10', 4819.700000000001)
('88', 4830.549999999999)
('20', 4836.859999999999)
('89', 4851.479999999999)
('95', 4876.840000000002)
('38', 4898.460000000002)
('76', 4904.209999999999)
('86', 4908.81)
('27', 4915.889999999999)
('18', 4921.27)
('53', 4945.299999999999)
('1', 4958.600000000001)
('51', 4975.22)
('16', 4979.06)
('30', 4990.72)
('28', 5000.709999999998)
('22', 5019.449999999999)
('29', 5032.529999999999)
('17', 5032.679999999999)
('60', 5040.709999999999)
('25', 5057.610000000001)
('19', 5059.4299999999985)
('81', 5112.709999999999)
('69', 5123.010000000001)
('65', 5140.3499999999985)
('11', 5152.290000000002)
('35', 5155.419999999999)
('40', 5186.429999999999)
('87', 5206.4)
('52', 5245.059999999999)
('26', 5250.4)
('62', 5253.3200000000015)
('33', 5254.659999999998)
('24', 5259.920000000003)
('93', 5265.750000000001)
('64', 5288.689999999996)
('90', 5290.409999999998)
('55', 5298.090000000002)
('9', 5322.649999999999)
('34', 5330.8)
('72', 5337.44)
('70', 5368.249999999999)
('43', 5368.83)
('92', 5379.280000000002)
('6', 5397.879999999998)
('15', 5413.510000000001)
('63', 5415.150000000001)
('58', 5437.7300000000005)
('32', 5496.050000000004)
('61', 5497.479999999998)
('85', 5503.43)
('8', 5517.240000000001)
('0', 5524.949999999998)
('41', 5637.62)
('59', 5642.89)
('42', 5696.840000000003)
('46', 5963.109999999999)
('97', 5977.189999999995)
('2', 5994.59)
('71', 5995.660000000003)
('54', 6065.389999999999)
('39', 6193.109999999999)
('73', 6206.199999999999)
('68', 6375.449999999997)